name: pmv
description: PMV is a CLI tool used to help manage package version in Dart projects with multiple packages
version: 1.0.0

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  collection: any
  glob: ^2.1.2
  path: ^1.8.0
  pubspec: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
