name: pmv
description: PMV is a CLI tool used to help manage package version in Dart projects with multiple packages
version: 0.0.2
repository: https://github.com/Chonli/pmv
issue_tracker: https://github.com/Chonli/pmv/issues

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  cli_completion: ^0.3.0
  collection: ^1.17.2
  glob: ^2.1.2
  mason_logger: ^0.2.6
  path: ^1.8.3
  pubspec: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  lints: ^2.1.0
  test: ^1.24.3

executables:
  pmv:
