name: pmv
description: PMV is a CLI tool used to help manage package version in Dart projects with multiple packages
version: 0.1.0
repository: https://github.com/Chonli/pmv
issue_tracker: https://github.com/Chonli/pmv/issues

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.0
  collection: any
  glob: ^2.1.2
  mason_logger: ^0.2.12
  path: ^1.9.0
  pub_updater: ^0.4.0
  pubspec2: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  lints: ^2.1.0
  test: ^1.24.3

executables:
  pmv:
